default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    database: udalba_development
    <<: *default

  solid_queue:
    database: udalba_development
    <<: *default

  cable:
    database: udalba_development
    <<: *default

test:
  primary:
    database: udalba_test
    <<: *default

  solid_queue:
    database: udalba_test
    <<: *default

  cable:
    database: udalba_test
    <<: *default

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
    <<: *default

  solid_queue:
    url: <%= ENV['DATABASE_URL'] %>
    <<: *default

  cable:
    url: <%= ENV['DATABASE_URL'] %>
    <<: *default

  cache:
    url: <%= ENV['DATABASE_URL'] %>
    <<: *default
