User.create!([
  {
    full_name: "Marco Valverde",
    rut: "12419397-4",
    birthdate: Date.parse("1972-10-03"),
    position: "Director Psicología",
    email_address: "marco.valverde@udalba.cl",
    password_digest: BCrypt::Password.create("124193"),
    phone_number: "56994378783",
    mesa: 6,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Julio Elzo",
    rut: "6639512-k",
    birthdate: Date.parse("1956-07-22"),
    position: "Director de Medicina",
    email_address: "julio.elzo@udalba.cl",
    password_digest: BCrypt::Password.create("663951"),
    phone_number: "56997410985",
    mesa: 1,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Susana Pintos Rojas",
    rut: "21824559-5",
    birthdate: Date.parse("1973-05-24"),
    position: "Directora de Admisión",
    email_address: "carmen.pintos@udalba.cl",
    password_digest: BCrypt::Password.create("218245"),
    phone_number: "56974300070",
    mesa: 1,
    campus: "La Serena",
    area: "Jefatura Administrativa"
  },
  {
    full_name: "Patricia Leiva",
    rut: "12542287-k",
    birthdate: Date.parse("1973-09-11"),
    position: "Secretaria de estudios psicología",
    email_address: "patricia.leiva@udalba.cl",
    password_digest: BCrypt::Password.create("125422"),
    phone_number: "56996380224",
    mesa: 6,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Fabián Díaz Flores",
    rut: "6817389-k",
    birthdate: Date.parse("1987-09-28"),
    position: "Director Asuntos Estudiantiles",
    email_address: "fabian.diaz@udalba.cl",
    password_digest: BCrypt::Password.create("681738"),
    phone_number: "56931461561",
    mesa: 2,
    campus: "La Serena",
    area: "Jefatura Administrativa"
  },
  {
    full_name: "Vanessa Véliz",
    rut: "19347347-4",
    birthdate: Date.parse("1996-01-05"),
    position: "Coordinadora de Biblioteca",
    email_address: "vanessa.veliz@udalba.cl",
    password_digest: BCrypt::Password.create("193473"),
    phone_number: "56981817527",
    mesa: 1,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Valentina Arancibia",
    rut: "19661863-5",
    birthdate: Date.parse("1998-01-09"),
    position: "Analista de Gestión Vicerrectoría",
    email_address: "valentina.arancibia@udalba.cl",
    password_digest: BCrypt::Password.create("196618"),
    phone_number: "56963148150",
    mesa: 2,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Daniela Ledezma",
    rut: "16552059-9",
    birthdate: Date.parse("1987-01-09"),
    position: "Periodista senior",
    email_address: "daniela.ledezma@udalba.cl",
    password_digest: BCrypt::Password.create("165520"),
    phone_number: "56987940254",
    mesa: 3,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Fabiana  Rivera",
    rut: "10438433-1",
    birthdate: Date.parse("1964-02-04"),
    position: "Secretaria FACSA",
    email_address: "fabiana.rivera@udalba.cl",
    password_digest: BCrypt::Password.create("104384"),
    phone_number: "56923819034",
    mesa: 4,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Johanna Díaz",
    rut: "17014736-7",
    birthdate: Date.parse("1988-07-26"),
    position: "Coordinadora Gestión de personas",
    email_address: "johanna.diaz@udalba.cl",
    password_digest: BCrypt::Password.create("170147"),
    phone_number: "56978001197",
    mesa: 5,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Carla Vargas",
    rut: "16442609-2",
    birthdate: Date.parse("1986-10-23"),
    position: "Coordinadora Tesorería",
    email_address: "carla.vargas@udalba.cl",
    password_digest: BCrypt::Password.create("164426"),
    phone_number: "56961912024",
    mesa: 6,
    campus: "La Serena",
    area: "Administrativos"
  },
  {
    full_name: "Luis Ríos",
    rut: "13214250-5",
    birthdate: Date.parse("1977-04-20"),
    position: "Director de Derecho",
    email_address: "luis.rios@udalba.cl",
    password_digest: BCrypt::Password.create("132142"),
    phone_number: "56989705704",
    mesa: 2,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Silvia Amanda Novoa Carrasco",
    rut: "9264143-0",
    birthdate: Date.parse("1963-03-26"),
    position: "Directora de Docencia",
    email_address: "silvia.novoa@udalba.cl",
    password_digest: BCrypt::Password.create("926414"),
    phone_number: "56932449918",
    mesa: 3,
    campus: "La Serena",
    area: "Jefatura Administrativa"
  },
  {
    full_name: "Karol Burrows",
    rut: "16874587-7",
    birthdate: Date.parse("1988-04-11"),
    position: "Directora de Ingeniería",
    email_address: "karol.burrows@udalba.cl",
    password_digest: BCrypt::Password.create("168745"),
    phone_number: "56935971562",
    mesa: 5,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Rodrigo Andrés Munizaga Urrutia",
    rut: "10759881-2",
    birthdate: Date.parse("1970-03-23"),
    position: "Director de Administración y finanzas",
    email_address: "rodrigo.munizaga@udalba.cl",
    password_digest: BCrypt::Password.create("107598"),
    phone_number: "56998921629",
    mesa: 4,
    campus: "La Serena",
    area: "Jefatura Administrativa"
  },
  {
    full_name: "Blanca Vera Cruz",
    rut: "10801990-5",
    birthdate: Date.parse("1971-02-20"),
    position: "Directora de Enfermería",
    email_address: "blanca.vera@udalba.cl",
    password_digest: BCrypt::Password.create("108019"),
    phone_number: "56992107363",
    mesa: 3,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Rubi Gatica ",
    rut: "13028376-4",
    birthdate: Date.parse("1976-07-11"),
    position: "Directora de Carrera Medicina Veterinaria",
    email_address: "rubi.gatica@udalba.cl",
    password_digest: BCrypt::Password.create("130283"),
    phone_number: "56967200879",
    mesa: 4,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Josselin Mondaca",
    rut: "13760664-k",
    birthdate: Date.parse("1980-09-25"),
    position: "Directora de Registro Curricular",
    email_address: "josselin.mondaca@udalba.cl",
    password_digest: BCrypt::Password.create("137606"),
    phone_number: "56988218506",
    mesa: 5,
    campus: "La Serena",
    area: "Jefatura Administrativa"
  },
  {
    full_name: "Virginia Veliz ",
    rut: "15912579-3",
    birthdate: Date.parse("1984-08-24"),
    position: "Secretaria de estudios Medicina",
    email_address: "virginia.veliz@udalba.cl",
    password_digest: BCrypt::Password.create("159125"),
    phone_number: "56991874892",
    mesa: 5,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Loredana Yutronic",
    rut: "15716130-k",
    birthdate: Date.parse("1983-07-26"),
    position: "Vicedecana de Fac. Ciencias de la Salud",
    email_address: "loredana.yutronic@udalba.cl",
    password_digest: BCrypt::Password.create("157161"),
    phone_number: "56991979223",
    mesa: 6,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Carolina Saldívar Apablaza",
    rut: "16565443-9",
    birthdate: Date.parse("1987-12-20"),
    position: "Directora de carrera Odontología",
    email_address: "carolina.saldivar@udalba.cl",
    password_digest: BCrypt::Password.create("165654"),
    phone_number: "56956681700",
    mesa: 4,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Wilfredo Peña",
    rut: "26811823-3",
    birthdate: Date.parse("1968-11-16"),
    position: "Auxiliar",
    email_address: "wilfredo.peña@udalba.cl",
    password_digest: BCrypt::Password.create("268118"),
    phone_number: "56957346847",
    mesa: 6,
    campus: "La Serena",
    area: "Auxiliares"
  },
  {
    full_name: "Carolina Contreras Saguas",
    rut: "14117791-5",
    birthdate: Date.parse("1981-06-27"),
    position: "Directora de Fonoaudiología",
    email_address: "carolina.contreras@udalba.cl",
    password_digest: BCrypt::Password.create("141177"),
    phone_number: "56993431132",
    mesa: 5,
    campus: "La Serena",
    area: "Directivos Académicos"
  },
  {
    full_name: "Claudia Rojas Díaz",
    rut: "13178277-2",
    birthdate: Date.parse("1976-12-13"),
    position: "Directora de Laboratorios",
    email_address: "claudia.rojas@udalba.cl",
    password_digest: BCrypt::Password.create("131782"),
    phone_number: "56994215763",
    mesa: 6,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "Pia Silva",
    rut: "9940193-1",
    birthdate: Date.parse("1980-08-20"),
    position: "Coordinadora de Campos Clínicos",
    email_address: "pia.silva@udalba.cl",
    password_digest: BCrypt::Password.create("994019"),
    phone_number: "56983616106",
    mesa: 1,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "Alexandra Castillo",
    rut: "18003097-2",
    birthdate: Date.parse("1992-03-26"),
    position: "Coordinadora de DDHH",
    email_address: "alexandra.castillo@udalba.cl",
    password_digest: BCrypt::Password.create("180030"),
    phone_number: "56997255850",
    mesa: 2,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "July Olivares",
    rut: "163258404-4",
    birthdate: Date.parse("1986-09-01"),
    position: "Coordinadora de Vinculación con el Medio",
    email_address: "july.olivares@udalba.cl",
    password_digest: BCrypt::Password.create("163258"),
    phone_number: "56962777485",
    mesa: 3,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "Patricio Pinto",
    rut: "16601946-k",
    birthdate: Date.parse("1987-03-13"),
    position: "Coordinador académico diurno",
    email_address: "patricio.pinto@udalba.cl",
    password_digest: BCrypt::Password.create("166019"),
    phone_number: "56977480134",
    mesa: 4,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "Iris Melys",
    rut: "5374766-3",
    birthdate: Date.parse("1947-05-23"),
    position: "Directora de Magíster",
    email_address: "iris.melys@udalba.cl",
    password_digest: BCrypt::Password.create("537476"),
    phone_number: "56998859860",
    mesa: 5,
    campus: "La Serena",
    area: "Administrativos Académicos"
  },
  {
    full_name: "Dere Nelson Gallardo",
    rut: "17980026-8",
    birthdate: Date.parse("1991-11-30"),
    position: "Docente jornada",
    email_address: "nelson.gallardo@udalba.cl",
    password_digest: BCrypt::Password.create("179800"),
    phone_number: "56979198402",
    mesa: 1,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Psic Luisa Fuentes",
    rut: "10524154-2",
    birthdate: Date.parse("1965-06-01"),
    position: "Docente jornada",
    email_address: "luisa.fuentes@aa.udalba.cl",
    password_digest: BCrypt::Password.create("105241"),
    phone_number: "56945671783",
    mesa: 2,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Medv Alejandra Covarrubias",
    rut: "15909955-5",
    birthdate: Date.parse("1985-05-02"),
    position: "Docente jornada",
    email_address: "alejandra.covarrubias@udalba.cl",
    password_digest: BCrypt::Password.create("159099"),
    phone_number: "56998633150",
    mesa: 3,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Inge Ailyn Rojas",
    rut: "16635735-7",
    birthdate: Date.parse("1987-04-28"),
    position: "Docente jornada",
    email_address: "ailyn.rojas@aa.udalba.cl",
    password_digest: BCrypt::Password.create("166357"),
    phone_number: "56941602080",
    mesa: 4,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Medi Evelyn Pallero",
    rut: "15976175-4",
    birthdate: Date.parse("1985-08-06"),
    position: "Docente jornada",
    email_address: "evelyn.pallero@udalba.cl",
    password_digest: BCrypt::Password.create("159761"),
    phone_number: "56975151374",
    mesa: 5,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Enfe Magdalena Ramirez",
    rut: "12232412-5",
    birthdate: Date.parse("1970-04-09"),
    position: "Docente jornada",
    email_address: "magdalena.ramirez@aa.udalba.cl",
    password_digest: BCrypt::Password.create("122324"),
    phone_number: "56979681985",
    mesa: 6,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Kine Claus Whesphal",
    rut: "15759685-3",
    birthdate: Date.parse("1984-10-01"),
    position: "Docente jornada",
    email_address: "claus.westphal@udalba.cl",
    password_digest: BCrypt::Password.create("157596"),
    phone_number: "56963854622",
    mesa: 3,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Nutd Natalia Diaz",
    rut: "18001912-k",
    birthdate: Date.parse("1991-09-25"),
    position: "Docente jornada",
    email_address: "natalia.diaz@udalba.cl",
    password_digest: BCrypt::Password.create("180019"),
    phone_number: "56999458520",
    mesa: 4,
    campus: "La Serena",
    area: "Docente Contratados"
  },
  {
    full_name: "Paola Peralta",
    rut: "17174574-8",
    birthdate: Date.parse("1989-06-25"),
    position: "Docente a Honorarios",
    email_address: "paola.peralta@aa.udalba.cl",
    password_digest: BCrypt::Password.create("171745"),
    phone_number: "56961592967",
    mesa: 1,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Psic Clint Diaz",
    rut: "15055497-7",
    birthdate: Date.parse("1982-10-16"),
    position: "Docente a Honorarios",
    email_address: "clint.diaz@aa.udalba.cl",
    password_digest: BCrypt::Password.create("150554"),
    phone_number: "56940215458",
    mesa: 2,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Hector Olguin",
    rut: "10112640-4",
    birthdate: Date.parse("1970-01-04"),
    position: "Docente a Honorarios",
    email_address: "hector.olguin@aa.udalba.cl",
    password_digest: BCrypt::Password.create("101126"),
    phone_number: "56945230006",
    mesa: 3,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Inge Jorge Medina",
    rut: "4504318-5",
    birthdate: Date.parse("1945-01-21"),
    position: "Docente a Honorarios",
    email_address: "jorge.medina@aa.udalba.cl",
    password_digest: BCrypt::Password.create("450431"),
    phone_number: "56985995009",
    mesa: 4,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Medi Marcela Cristina Pineda Polanco, Doc.H.",
    rut: "16476042-1",
    birthdate: Date.parse("1986-06-16"),
    position: "Docente a Honorarios",
    email_address: "mcpineda@udalba.cl",
    password_digest: BCrypt::Password.create("164760"),
    phone_number: "56994141510",
    mesa: 5,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Guacolda Del Carmen Galvez Castillo",
    rut: "8748702-4",
    birthdate: Date.parse("1961-06-11"),
    position: "Docente a Honorarios",
    email_address: "guacolda.galvez@aa.udalba.cl",
    password_digest: BCrypt::Password.create("874870"),
    phone_number: "56975284540",
    mesa: 6,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Fgra Carlos Barraza",
    rut: "13425513-7",
    birthdate: Date.parse("1978-10-01"),
    position: "Docente a Honorarios",
    email_address: "carlos.barraza@aa.udalba.cl",
    password_digest: BCrypt::Password.create("134255"),
    phone_number: "56934571226",
    mesa: 5,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Constanza Pulgar Banda",
    rut: "16187927-4",
    birthdate: Date.parse("1985-09-04"),
    position: "Docente a Honorarios",
    email_address: "constanza.pulgar@aa.udalba.cl",
    password_digest: BCrypt::Password.create("161879"),
    phone_number: "56981712854",
    mesa: 6,
    campus: "La Serena",
    area: "Docente Honorarios"
  },
  {
    full_name: "Tecm Jhosstin Valera",
    rut: "21209773-k",
    birthdate: Date.parse("2003-01-08"),
    position: "Estudiante",
    email_address: "jrvalera@udalba.cl",
    password_digest: BCrypt::Password.create("212097"),
    phone_number: "56993930441",
    mesa: 1,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Medv Ayrin Rojas Fuentes",
    rut: "17451981-1",
    birthdate: Date.parse("1989-12-13"),
    position: "Estudiante",
    email_address: "amrojas@udalba.cl",
    password_digest: BCrypt::Password.create("174519"),
    phone_number: "56936832490",
    mesa: 2,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Enfe Gionavanny Tapia ",
    rut: "21333036-5",
    birthdate: Date.parse("1993-04-21"),
    position: "Estudiante",
    email_address: "GITAPIAF@UDALBA.CL",
    password_digest: BCrypt::Password.create("213330"),
    phone_number: "56974608424",
    mesa: 3,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Psic Patricio Fuentes",
    rut: "13814472-0",
    birthdate: Date.parse("1980-11-20"),
    position: "Estudiante",
    email_address: "pffuentes@udalba.cl",
    password_digest: BCrypt::Password.create("138144"),
    phone_number: "56986459425",
    mesa: 4,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Kine Erick Silva",
    rut: "18667023-k",
    birthdate: Date.parse("1994-04-11"),
    position: "Estudiante",
    email_address: "esilvas@udalba.cl",
    password_digest: BCrypt::Password.create("186670"),
    phone_number: "56955287779",
    mesa: 5,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Cind Bastián Leandro Araya Valenzuela",
    rut: "20797652-0",
    birthdate: Date.parse("2001-07-31"),
    position: "Estudiante",
    email_address: "esilvas@udalba.cl",
    password_digest: BCrypt::Password.create("207976"),
    phone_number: "56953622788",
    mesa: 6,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Benjamin Ramirez Araya",
    rut: "21608307-5",
    birthdate: Date.parse("2004-06-30"),
    position: "Estudiante",
    email_address: "dramireza@udalba.cl",
    password_digest: BCrypt::Password.create("216083"),
    phone_number: "56982181457",
    mesa: 1,
    campus: "La Serena",
    area: "Estudiantes"
  },
  {
    full_name: "Francisco Javier Pizarro Muñoz",
    rut: "17013826-0",
    birthdate: Date.parse("1989-06-29"),
    position: "Titulado Psicologia",
    email_address: "FJPIZARRO89@GMAIL.COM",
    password_digest: BCrypt::Password.create("170138"),
    phone_number: "56986984890",
    mesa: 1,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Alejandro Antonio Luna Arellano",
    rut: "16557367-6",
    birthdate: Date.parse("1987-04-30"),
    position: "Titulado Med. Veterinaria",
    email_address: "alunaarellano@gmail.com",
    password_digest: BCrypt::Password.create("165573"),
    phone_number: "56992390302",
    mesa: 2,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Felipe Ponce Tabilo",
    rut: "19771905-2",
    birthdate: Date.parse("1988-09-05"),
    position: "Titulado Kinesiologia",
    email_address: "fsponcet@gmail.com",
    password_digest: BCrypt::Password.create("197719"),
    phone_number: "56957427171",
    mesa: 3,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Felipe Acevedo Vial",
    rut: "19451795-5",
    birthdate: Date.parse("1987-07-09"),
    position: "Titulado Odontologia",
    email_address: "fiacevedo@udalba.cl",
    password_digest: BCrypt::Password.create("194517"),
    phone_number: "56982190544",
    mesa: 4,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Sebastian Galleguillo Galleguillos",
    rut: "18003092-1",
    birthdate: Date.parse("1992-03-13"),
    position: "Titulado Ingenieria Civil Mina",
    email_address: "sebastian.galleguillo@udalba.cl",
    password_digest: BCrypt::Password.create("180030"),
    phone_number: "56962960111",
    mesa: 5,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Matias Maureira",
    rut: "19475383-7",
    birthdate: Date.parse("1996-07-10"),
    position: "Titulado Ingenieria Civil Mina",
    email_address: "mmaureira1996@gmail.com",
    password_digest: BCrypt::Password.create("194753"),
    phone_number: "56984638712",
    mesa: 2,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Jose Miguel Zamora Cortes",
    rut: "19348850-1",
    birthdate: Date.parse("1996-08-05"),
    position: "Titulado  Geologìa",
    email_address: "jzamoracortes9@gmail.com",
    password_digest: BCrypt::Password.create("193488"),
    phone_number: "56941084574",
    mesa: 6,
    campus: "La Serena",
    area: "Titulados"
  },
  {
    full_name: "Elio Elorza Parada ",
    rut: "8170638-7",
    birthdate: Date.parse("1959-03-09"),
    position: "Vicerrector de sede La Serena",
    email_address: "elio.elorza@udalba.cl",
    password_digest: BCrypt::Password.create("817063"),
    phone_number: "000000000",
    mesa: 2,
    campus: "La Serena",
    area: "Vicerrector"
  },
  {
    full_name: "Rafael Rosell Aiquel",
    rut: "8350066-2",
    birthdate: Date.parse("1959-11-24"),
    position: "Rector",
    email_address: "rafael.rosell@udalba.cl",
    password_digest: BCrypt::Password.create("835006"),
    phone_number: "000000000",
    mesa: 1,
    campus: "La Serena",
    area: "Rector"
  },
  {
    full_name: "Guido Meller Mayr",
    rut: "4540996-1",
    birthdate: Date.parse("1940-10-15"),
    position: "Miembro Directorio",
    email_address: "guido.meller@udalba.cl",
    password_digest: BCrypt::Password.create("454099"),
    phone_number: "000000000",
    mesa: 3,
    campus: "La Serena",
    area: "Directorio"
  }
])
